### ISSUE TITLE
Modify layout based on storyline

### ISSUE THREAD

**Issue by tbergama** [tascha/DA2I-Dashboard#33]

**Comment by mariagarrido** [comment]
Please revise the storyline here for the order of the graphs. Manisha and Tom, while you are working on the layout please make sure the flow of the story makes sense. I divided the dashboard into three sections: Access, Use, and Affordability. Working on the brief explanation that will accompany the titles. The order is at the end of connectivity storyline: https://docs.google.com/document/d/1R1mVQoQx4IR1m1CelabdbBsMibbxpR5H6GJBHzSSpQo/edit#
